# Dependabot configuration
version: 2
updates:

  # Maintain dependencies via npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "18:00"
      timezone: "America/Cancun"
    labels:
      - "review"
      - "dependencies"
    rebase-strategy: "auto"
    versioning-strategy: "auto"
    commit-message:
      prefix: "build(deps)"
      include: "scope"
    allow:
      - dependency-type: "production"
    # ignore:
    #   -


  # Maintain dependencies via npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "20:00"
      timezone: "America/Cancun"
    labels:
      - "review"
      - "dependencies"
    rebase-strategy: "auto"
    versioning-strategy: "auto"
    commit-message:
      prefix: "build(deps-dev)"
      include: "scope"
    allow:
      - dependency-type: "development"
    # ignore:
    #   -


  # Maintain dependencies for GitHub actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "review"
      - "github-action-deps"
      - "ci"
    commit-message:
      prefix: "ci(deps)"
      include: "scope"
